### ISSUE TITLE
Bug: set property failed caused by too many open files

### ISSUE THREAD

**Issue by josh-hsu** [josh-hsu/PokemonGoGo#1]
Severity:
Critical (4) - bug that need to be resolved in first priority

Reproduce rate:
10/10

Calltrace:
08-21 16:19:11.604 13887-14574/com.mumu.pokemongogo D/PokemonGoGo: RANDOM lat = 1.4314194890938873E-6, long = 1.4314194890938873E-6
08-21 16:19:11.606 13887-14574/com.mumu.pokemongogo W/System.err: java.io.IOException: Error running exec(). Command: [/system/bin/sh, -c, setprop persist.asus.fakegps.lat 25.042594581033885] Working Directory: null Environment: null
08-21 16:19:11.606 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:211)
08-21 16:19:11.607 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.Runtime.exec(Runtime.java:174)
08-21 16:19:11.607 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.Runtime.exec(Runtime.java:129)
08-21 16:19:11.607 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.location.PropertyService.runCommandNoOutput(PropertyService.java:66)
08-21 16:19:11.607 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.location.PropertyService.setSystemProperty(PropertyService.java:26)
08-21 16:19:11.607 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.location.FakeLocationManager.setLatitude(FakeLocationManager.java:157)
08-21 16:19:11.607 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.location.FakeLocationManager.walkPace(FakeLocationManager.java:128)
08-21 16:19:11.607 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.HeadService$StartAutoIncubatingThread.run(HeadService.java:554)
08-21 16:19:11.607 13887-14574/com.mumu.pokemongogo W/System.err: Caused by: java.io.IOException: Too many open files
08-21 16:19:11.609 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.ProcessManager.exec(Native Method)
08-21 16:19:11.609 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
08-21 16:19:11.609 13887-14574/com.mumu.pokemongogo W/System.err:   ... 7 more
08-21 16:19:11.610 13887-14574/com.mumu.pokemongogo W/System.err: java.io.IOException: Error running exec(). Command: [/system/bin/sh, -c, setprop persist.asus.fakegps.acc 9.46792157169074] Working Directory: null Environment: null
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:211)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.Runtime.exec(Runtime.java:174)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.Runtime.exec(Runtime.java:129)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.location.PropertyService.runCommandNoOutput(PropertyService.java:66)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.location.PropertyService.setSystemProperty(PropertyService.java:26)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.location.FakeLocationManager.setAccuracy(FakeLocationManager.java:169)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.location.FakeLocationManager.walkPace(FakeLocationManager.java:133)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at com.mumu.pokemongogo.HeadService$StartAutoIncubatingThread.run(HeadService.java:554)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err: Caused by: java.io.IOException: Too many open files
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.ProcessManager.exec(Native Method)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
08-21 16:19:11.621 13887-14574/com.mumu.pokemongogo W/System.err:   ... 7 more

**Comment by josh-hsu** [comment]
Fixed
